- name: Install Apache 2
  apt:
    pkg: '{{item}}'
    state: 'present'
  with_items: '{{apt.dependencies}}'
  become: yes

- name: Enable Apache proxy modules
  apache2_module:
    state: present
    name: '{{item}}'
  with_items: '{{modules}}'
  notify:
    - Restart apache2
  become: yes

- name: Copy virtualhost configuration
  template:
    src: default-virtualhost.conf.j2
    dest: /etc/apache2/sites-available/000-default.conf
  notify:
    - Restart apache2
  become: yes

- name: Ensure Apache is started
  service:
    name: 'apache2'
    state: 'started'
  become: yes
